### ISSUE TITLE
updated dependencies cause error

### ISSUE THREAD

**Issue by vincent-hanlon** [daewoooo/StrandPhaseR#5]
First off, I use StrandPhaseR frequently and it’s great---so thank you!

I noticed a small problem with the installation of StrandPhaseR. When XVector=0.32.0 and IRanges=2.26.0 are used, lines 96-101 of loadMatrices.R throw an error. This is not a problem when XVector=0.28.0 and IRanges=2.22.1 are used. The error happens because previous lines like line 91,

`df.pilesCrick <- as(piles.crick, "data.frame")`,

assign the only column in the new dataframe df.pilesCrick the column name "x" when older versions of XVector/IRanges are used, but does not assign it a column name when newer versions are used. This causes an error on lines 96-101 when expressions like

`df.pilesCrick$x` 

are used to access the first column of the dataframe. That is, in some versions, column "x" doesn't exist and the expression is NULL. 

So following the installation instructions on the README with the current versions of Bioconductor packages does not always produce a working version of StrandPhaseR, since up-to-date versions of Bioconductor packages are installed by default. 

Maybe the easiest solution would be to replace "$x" with "[,1]" in lines 96-101 of loadMatrices.R, as well as lines 80-85 of fillGaps.R. By my tests, this allows current versions of Bioconductor packages to be used when installing StrandPhaseR.

**Comment by daewoooo** [comment]
Hi thanks a lot for pointing out this. I have seen the similar error a while ago. I have fixed this error in the developmental version of StrandPhaseR package. Now I have also updated the loadMatrices.R function in the master branch. Try reinstall the master version. If it is not working please you devel version. Devel version now includes some new development and I hope to merge with master soon. Hope this helps.

**Comment by vincent-hanlon** [comment]
?Hi David,

I just tested the bug fix and it works. Thanks!

Vincent

________________________________
