### ISSUE TITLE
Dependencies "zoo" and "BSgenome" don't install automatically

### ISSUE THREAD

**Issue by vincent-hanlon** [daewoooo/StrandPhaseR#8]
When doing a fresh install of StrandPhaseR using `devtools::install_github()`, the installation fails if "zoo" and "BSgenome" were not pre-installed. 

Luckily, there is a very easy fix: just add the two packages under the "Imports:" heading in the "DESCRIPTION" file:

        zoo,
        BSgenome,

This will allow "devtools" to install the two dependencies as it install StrandPhaseR. I tested this change once and it worked.

**Comment by daewoooo** [comment]
Resolved! Thank you for pointing this out.
